spring:
  application:
    name: SpringBootStudentMicroservice
  web:
    error:
      whitelabel:
        enabled: false
eureka:
  client:
    service-url:
     default-zone: http://localhost:8761/eureka/
    jersey:
      enabled: false
server:
  port: 2222