spring:
  application:
    name: StudentMicroserviceClient
  web:
    error:
      whitelabel:
        enabled: false
eureka:
  client:
   service-url:
        default-zone: http://localhost:1111/eureka/
 
server:
  port: 3333

